import userRoutes from "../modules/user/user.route";
import authRoutes from "../modules/auth/auth.route";
import courseRoutes from "../modules/course/course.route";
import sectionRoutes from "../modules/section/section.route";
import lectureRoutes from "../modules/lecture/lecture.route";
import lessonRoutes from "../modules/lesson/lesson.route";
import quizRoutes from "../modules/quiz/quiz.route";
import reviewRoutes from "../modules/review/review.route";
import enrollmentRoutes from "../modules/enrollment/enrollment.route";
import certificateRoutes from "../modules/certificate/certificate.route";
import wishlistRoutes from "../modules/wishlist/wishlist.route";
import notificationRoutes from "../modules/notification/notification.route";
import commentRoutes from "../modules/comment/comment.route";
import liveSessionRoutes from "../modules/live-session/live-session.route";
import paymentRoutes from "../modules/payment/payment.route";
import cartRoutes from "../modules/cart/cart.route";
import categoryRoutes from "../modules/category/category.route";
import progressRoutes from "../modules/progress/progress.route";
import gamificationRoutes from "../modules/gamification/gamification.route";
import express from "express";

const router = express.Router();

router.use("/users", userRoutes);
router.use("/auth", authRoutes);
router.use("/courses", courseRoutes);
router.use("/sections", sectionRoutes);
router.use("/lectures", lectureRoutes);
router.use("/lessons", lessonRoutes);
router.use("/quizzes", quizRoutes);
router.use("/reviews", reviewRoutes);
router.use("/progress", progressRoutes);
router.use("/enrollments", enrollmentRoutes);
router.use("/certificates", certificateRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/notifications", notificationRoutes);
router.use("/comments", commentRoutes);
router.use("/live-sessions", liveSessionRoutes);
router.use("/gamification", gamificationRoutes);
router.use("/payments", paymentRoutes);
router.use("/cart", cartRoutes);
router.use("/categories", categoryRoutes);

export default router;
